name: Build and Deploy

on:
  push:
    branches:
      - deploy
  workflow_dispatch:

jobs:
    FrontDeploy:
        name: FrontDeploy
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Setup Node
              uses: actions/setup-node@v2
              with:
                  node-version: 18.x
            - name: Build
              run: |
                  npm install
                  npm install -g firebase-tools
                  npm run build
            - name: Deploy to Firebase Hosting
              run: |
                  firebase deploy --token $FIREBASE_TOKEN --project $FIREBASE_PROJECT_ID --only hosting
              env:
                  FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
                  FIREBASE_PROJECT_ID: ${{ env.FIREBASE_PROJECT_ID}}

